### ISSUE TITLE
no check for manage_repo

### ISSUE THREAD

**Issue by m0n0lith** [elastic/puppet-kibana#1]
## Bug Report

* Module version:  0.1.0
* Puppet version: 4.9.2
* OS and version: Centos 7.3.1611

### Bug description

Expected behavior:
Do not install Elastic.co kibana repo. As I have a local copy of the Elastic repo.

Observed behavior:
Installs Kibana repo even when $manage_repo is set to 'false'.

Example manifest:
`class { '::kibana':
  include profile::yum::elk
  include profile::nginx
    manage_repo => false,
    ensure      => $profile::kibana::base::kibana_version,
    config      => {
      'kibana.defaultAppId'          => $profile::kibana::base::kibana_defaultappid,
      'elasticsearch.requestTimeout' => $profile::kibana::base::kibana_reqtime,
    }
  }
  kibana_plugin { 'x-pack':
    url => "http://katello01.infra.aza.nu/pulp/isos/Default_Organization-ELK-xpack/x-pack-${profile::kibana::base::kibana_version}.zip",
  }`

Puppet run logs:
puppet-agent[2223]: (/Stage[main]/Kibana::Install/Yumrepo[kibana]/ensure) created
puppet-agent[2223]: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install tmux' returned 1: One of the configured repositories failed (Elastic 5.x repository),
puppet-agent[2223]: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install tmux' returned 1: One of the configured repositories failed (Elastic 5.x repository),

Info:
Would like to say that I do not find any check in install.pp towards if manage_repo is true or not. And seems to have the Elastic.co URL added anyway.

**Comment by tylerjl** [comment]
You're absolutely right, I completely forgot to handle the class parameter in the install class. Thank you so much for the report! I'll fix it.

**Comment by tylerjl** [comment]
Resolved (and tests added) in ee7c3944c81. Will be in the next release.
