### ISSUE TITLE
Kibana module sub-classes aren't properly contained

### ISSUE THREAD

**Issue by mzahorik** [elastic/puppet-kibana#12]
I am maintaining my own repositories and require that the kibana class proceed after the repository is created.

class { 'kibana':
  [.. snip ..]
  require => Yumrepo['elastic-repo'],
}

Expected behavior:

kibana::install will execute after the resource yumrepo{'elastic-repo': }

Observed behavior:

kibana::install executes before the resource yumrepo{'elastic-repo': } and therefore the yum install fails.

Root cause:

The kibana::install, kibana::config, and kibana::service sub-classes are not contained by the kibana class.  Therefore they do not follow the dependency on the parent class.

PR #11 is submitted to correct this behavior.

**Comment by tylerjl** [comment]
Thanks for the report @mzahorik - just so I'm aware when we do make the change, once this module goes 4.x-only, we should be able to `contain` all those classes and forgot about following the anchor pattern, correct?

**Comment by tylerjl** [comment]
Merged in #11

**Comment by mzahorik** [comment]
@tylerjl Yes, I took a cue from the other elastic/elasticsearch module and used anchors for 3.8 compatibility, but using contain is the go-forward best practice as I understand it.
