### ISSUE TITLE
Support apt module 4.x.x

### ISSUE THREAD

**Issue by ktham** [elastic/puppet-kibana#13]
I was starting to write my own puppet module for the ELK stack, but realized it's already done by you guys at elastic. However, I'm not able to use this kibana module because this module is incompatible with apt module 4.1.0.

The [puppet-elasticsearch](https://github.com/elastic/puppet-elasticsearch/blob/master/metadata.json#L14) module however has this:

```
{
      "name": "puppetlabs/apt",
      "version_requirement": ">= 2.0.0 < 5.0.0"
}
```

Can we update puppet-kibana to support the same?

**Comment by tylerjl** [comment]
Hey @ktham, I've got a branch baking in CI right now to verify things look good and I'll merge and release once everything passes. Thanks!
