### ISSUE TITLE
How to install Kibana 4?

### ISSUE THREAD

**Issue by cristianbalan-mf** [elastic/puppet-kibana#19]
I'm attempting to replace the lesaux/kibana4 module with yours and before upgrading the current Kibana 4.5.4, I want to make sure that I can adapt my code to this module.
In ensuring 4.5.4 only, I get this error:
```
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_mkdir - /etc/kibana/kibana.yml20171220-18310-199jtgn.lock at /etc/puppetlabs/code/environments/vagrant/modules/kibana/manifests/config.pp:19
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_mkdir - /etc/kibana/kibana.yml20171220-18310-199jtgn.lock at /etc/puppetlabs/code/environments/vagrant/modules/kibana/manifests/config.pp:19
Wrapped exception:
No such file or directory @ dir_s_mkdir - /etc/kibana/kibana.yml20171220-18310-199jtgn.lock
Error: /Stage[main]/Kibana::Config/File[/etc/kibana/kibana.yml]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory @ dir_s_mkdir - /etc/kibana/kibana.yml20171220-18310-199jtgn.lock at /etc/puppetlabs/code/environments/vagrant/modules/kibana/manifests/config.pp:19
```
So is looking in /etc/kibana while it should only stick to /opt/kibana as I'm using the old 4.x. This is what happens in the /etc/apt/sources.list.d/
```
root@vagrant:/etc/apt# grep -inr "elastic" .
./sources.list.d/elasticsearch.list:3:deb http://packages.elastic.co/elasticsearch/2.x/debian stable main
./sources.list.d/**kibana-4.5.list**:3:deb http://packages.elastic.co/kibana/4.5/debian stable main
./sources.list.d/**kibana.list**:3:deb https://artifacts.elastic.co/packages/6.x/apt stable main
```

The readme doesn't cover this but I figure out that your default repo_version is set to `6.x` so I'm overwriting that:
```
  class { 'kibana':
    repo_version => '4.x',
    ensure       => '4.5.4',
    config       => {
      'server.host' => $elasticsearch_host,
      'server.port' => '9200',
    }
  }
```
But then I get:
`Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Kibana]: parameter 'repo_version' expects a match for Variant[Enum['5.x', '6.x'], Pattern[/^4\.(1|[4-6])$/]], got '4.x' at /etc/puppetlabs/code/environments/vagrant/site/profile/manifests/kibana.pp:7:3 on node dev-logstation.mobilefun.co.uk`

A little help would be appreciated.

**Comment by cristianbalan-mf** [comment]
Ok, `repo_version => '4.5'` is the answer. I'm sure the documentation could be improved. Thank for your module.

**Comment by tylerjl** [comment]
Apologies for any confusion @cristianbalan-mf, commit 05f7858 attempts to clear up any ambiguities.
