### ISSUE TITLE
Plugin install should either update existing plugin or break with error

### ISSUE THREAD

**Issue by gna582** [elastic/puppet-kibana#33]
## Bug Report
Plugin install should either update existing plugin or break with error. Currently it fails silently and puppetrun seems to be successful.

* Module version:
6.3.0
* Puppet version:
4.10.12
* OS and version:
Linux mtis-es-portal-wfe-qa001 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64 GNU/Linux
### Bug description

Expected behavior:
kibana_plugin should update existing plugin or break with error. 6.4.2-15 should be installed.

Observed behavior:
kibana_plugin does not update the existing plugin and continues without failing. 6.3.0-13 is still installed.

Example manifest:
```
  kibana_plugin { 'searchguard':
    url     => 'https://oss.sonatype.org/service/local/repositories/releases/content/com/floragunn/search-guard-kibana-plugin/6.4.2-15/search-guard-kibana-plugin-6.4.2-15.zip',
  }
```

Puppet run logs:

Output from puppetboard and thus somewhat convoluted. sry
```
Oct 11 2018 - 17:34:17 | /Stage[main]/Profile::Elasticsearch::Elasticsearch/Elasticsearch::Plugin[com.floragunn:search-guard-6:6.4.2-23.1]/Elasticsearch_plugin[com.floragunn:search-guard-6:6.4.2-23.1]/ensure 
created
```

**Comment by gna582** [comment]
I am not 100% sure but maybe its the same problem like https://github.com/elastic/puppet-kibana/issues/20 ?
The puppetcode before was the same except the different url with 6.3.0-13 instead of 6.4.2-15

**Comment by tylerjl** [comment]
@gna582 as [the documentation notes](https://forge.puppet.com/elastic/kibana#kibana-5x--6x), it's important to pass the version that the plugin should install in order to let the `puppet_kibana` resource know what version it's supposed to be managing. Have you passed this parameter/have an example manifest to share?

**Comment by gna582** [comment]
@tylerjl Ah! Sry my bad. I only read the documentation when building up the cluster but not when upgrading. Got confused as the elasticsearch plugin module works differently.

Imho that parameter should be required if not having it has these strange results when upgrading and there is no real downside to specifying it on cluster creation.

Thank you!

**Comment by gna582** [comment]
@tylerjl Ah! Sry my bad. I only read the documentation when building up the cluster but not when upgrading. Got confused as the elasticsearch plugin module works differently.

Imho that parameter should be required if not having it has these strange results when upgrading and there is no real downside to specifying it on cluster creation.

Thank you!
