### ISSUE TITLE
Puppet 3.8 Support

### ISSUE THREAD

**Issue by austin-l** [elastic/puppet-kibana#4]
## Feature Request
Puppet 3.8 Support
### Feature Description
Support for Puppet 3.8 at least in the short to mid term aligning with the other elastic 5.x puppet module requirements.

**Comment by ralfbosz** [comment]
Puppet 3.8 is EOL since 31-dec-2016

**Comment by tylerjl** [comment]
Just FYI, we're planning on moving all the Elastic Puppet modules over to 4.x only down the road (probably in-line with a major version release of Elasticsearch). Because of this, I don't know that we'll be dedicating many cycles to backporting 3.8 support to the modules. There's no hard rule against accepting 3.8 compatability PRs into a separate  branch or anything if someone wants to put in the work for it.

**Comment by wonkyto** [comment]
I understand that you need to move forward but I'm sure we aren't the only organisation to use Red Hat Satellite to manage our environment, and the very latest version ships with Puppet 3.8.6. I don't mean to sound whiny but major changes like upgrading Satellite is a very slow and difficult process for a large enterprise, and once you only support Puppet v4, we'll have no where to go.

Despite the speed at which Elastic moves at, I do try to keep our environment near the release versions, however it's now the supporting puppet modules which are preventing us from keeping up to date **and** have an automated environment.

**Comment by tylerjl** [comment]
@wonkyto I can sympathize, and having worked in slow-moving environments in the past is part of the reason I haven't pushed puppet-elasticsearch to Puppet 4.x only yet. There's lots of people still on 3.x from what I've seen.

However, it's getting more and more difficult to develop modules now that Puppetlabs, Inc. has put 3.x to bed after its end-of-life date. Most of the tooling is moving onto 4.x, and although we can still develop modules on 3.x, it's only a matter of time. The upstream yum repos from Puppetlabs help with getting 4.x on platforms like CentOS 6, but I understand some environments have pretty strict requirements.

Anyway, I guess this is a long way of saying that we hear your concerns and there's no hard cutoff yet. Modules like this one that were built from the ground up for 4.x were able to get built due in part to the low friction of building something on the latest puppet version, so if someone wants to backport 3.8 support (including testing, documentation, etc.) then I wouldn't stop it, but somewhere down the road we'll be 4.x-only across the board for the puppet modules.

**Comment by soxwellfb** [comment]
So far, all I can see that makes this module not work in Puppet 3.8 is the variable typing. Haven't got the spec to build yet, due to the required Gems and my inexperience with this part of puppet. I'll poke at it a bit more, as I need this.

**Comment by tylerjl** [comment]
A non-comprehensive list of likely changes to backport to 3.8:

* Type annotations (replaced with stdlib module validate_* functions)
* Replacing `puppet-strings` (which is currently used for inline documentation - it auto-generates documentation as well)
* Add acceptance tests for 3.8 (right now all acceptance tests run against 4.x)
* In general there are likely many gems that need to be updated in `Gemfile`

**Comment by soxwellfb** [comment]
Okay, so far:
* replaced the type annotations
* removed autobefore relationship reference of out of the plugins type
* made a couple of changes to the Gemfile
* made the existing`puppet-strings` inline documentation adhere to the Puppet 3 standard documented here: https://github.com/puppetlabs/puppet-strings
* got my branch passing the existing acceptance tests on Travis-CI

Waiting on management to OK me signing the CLA before I create a pull request.

**Comment by tylerjl** [comment]
This has been implemented in #9 (thanks @soxwellfb!) and will be released shortly.

**Comment by austin-l** [comment]
This is great.  Thanks @soxwellfb and @tylerjl

**Comment by Keysuke** [comment]
It looks like Puppet 3 does not support dashes in dependencies, as stated [here](https://docs.puppet.com/puppet/3.8/modules_publishing.html#dependencies-in-metadatajson).
```
Warning: Missing dependency 'puppetlabs-apt':
  'elastic-kibana' (v0.3.0) requires 'puppetlabs-apt' (>= 2.0.0 < 3.0.0)
Warning: Missing dependency 'puppetlabs-stdlib':
  'elastic-kibana' (v0.3.0) requires 'puppetlabs-stdlib' (>= 4.5.0 < 5.0.0)
/etc/puppet/modules
├── elastic-kibana (v0.3.0)
├── puppetlabs-apt (v2.4.0)
└── puppetlabs-stdlib (v4.17.0)
```
Could you change the dashes in `metadata.json` into slashes ?
