### ISSUE TITLE
Secure /etc/kibana/kibana.yml

### ISSUE THREAD

**Issue by varac** [elastic/puppet-kibana#6]
## Feature Request

Currently, `/etc/kibana/kibana.yml` is world-readable.
Please make it RW only for the `elasticsearch` user.

### Feature Description

When storing credentials inside kibana.yml it shoul not be readable by any other user than the `elasticsearch` user for security reasons.

**Comment by tylerjl** [comment]
Thanks for the issue @varac. There's no guarantee that Elasticsearch will be on the same system as a host running Kibana, but the Kibana packages do create a `kibana` system user that the service runs under. Would changing the permissions to `0660` for the `kibana:kibana` or `root:root` work?

**Comment by varac** [comment]
@tylerjl Sorry, I was not looking properly. It should indeed get the permissions and ownership you are proposing.

**Comment by varac** [comment]
Thx !
